@extends("layouts.admin")
@section("title", "Tambah Jadwal")
@section("content")
@php $ready = $karyawan->isNotEmpty() && $shifts->isNotEmpty() && $locations->isNotEmpty(); @endphp
<div class="mx-auto max-w-3xl">
    <a href="{{ route('admin.jadwal.index') }}" class="mb-4 inline-flex items-center gap-1.5 text-sm font-medium text-stone-500 transition hover:text-amber-700"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7"/></svg>Kembali ke jadwal</a>
    @if($errors->any())<div class="mb-5 flex items-start gap-3 rounded-2xl border border-red-200 bg-red-50 px-5 py-3.5 text-sm text-red-700"><svg class="mt-0.5 h-5 w-5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 9v2m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg><ul class="list-disc pl-4">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    @if(!$ready)<div class="mb-5 flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 px-5 py-3.5 text-sm text-amber-800"><svg class="mt-0.5 h-5 w-5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 9v2m0 4h.01M5.07 19h13.86a2 2 0 001.71-3L13.71 4a2 2 0 00-3.42 0L3.36 16a2 2 0 001.71 3z"/></svg><span>Jadwal membutuhkan karyawan aktif, shift aktif, dan lokasi aktif. Lengkapi master data terlebih dahulu.</span></div>@endif

    <form method="POST" action="{{ route('admin.jadwal.store') }}" class="overflow-hidden rounded-3xl border border-white/70 bg-white/80 shadow-sm backdrop-blur">@csrf
        <div class="flex items-center gap-4 border-b border-stone-100 px-7 py-5" style="background: linear-gradient(120deg, #faf5ef, #f5ede3);"><div class="flex h-12 w-12 items-center justify-center rounded-2xl text-white shadow-lg" style="background: linear-gradient(135deg, #f59e0b, #d97706);"><svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="1.9"><path stroke-linecap="round" stroke-linejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/></svg></div><div><h3 class="text-base font-extrabold text-stone-800">Penempatan Karyawan</h3><p class="text-xs text-stone-400">Satu karyawan hanya dapat memiliki satu shift per tanggal operasional.</p></div></div>
        <div class="space-y-5 px-7 py-6">
            <div><label class="mb-1.5 block text-sm font-semibold text-stone-700">Karyawan</label><select name="karyawan_id" required class="w-full rounded-2xl border border-stone-200 bg-white px-4 py-3 text-sm outline-none transition focus:border-amber-500 focus:ring-4 focus:ring-amber-500/15"><option value="">-- Pilih Karyawan --</option>@foreach($karyawan as $k)<option value="{{ $k->id }}" {{ old('karyawan_id') == $k->id ? 'selected' : '' }}>{{ $k->nama_lengkap }} — {{ $k->jabatan }}</option>@endforeach</select>@error('karyawan_id')<p class="mt-1 text-xs text-red-500">{{ $message }}</p>@enderror</div>
            <div><label class="mb-1.5 block text-sm font-semibold text-stone-700">Tanggal Operasional</label><input type="date" name="tanggal_operasional" value="{{ old('tanggal_operasional', date('Y-m-d')) }}" required class="w-full rounded-2xl border border-stone-200 bg-white px-4 py-3 text-sm outline-none transition focus:border-amber-500 focus:ring-4 focus:ring-amber-500/15">@error('tanggal_operasional')<p class="mt-1 text-xs text-red-500">{{ $message }}</p>@enderror</div>
            <div class="grid grid-cols-1 gap-5 sm:grid-cols-2">
                <div><label class="mb-1.5 block text-sm font-semibold text-stone-700">Shift</label><select name="shift_id" required class="w-full rounded-2xl border border-stone-200 bg-white px-4 py-3 text-sm outline-none transition focus:border-amber-500 focus:ring-4 focus:ring-amber-500/15"><option value="">-- Pilih Shift --</option>@foreach($shifts as $shift)<option value="{{ $shift->id }}" {{ old('shift_id') == $shift->id ? 'selected' : '' }}>{{ $shift->nama }} ({{ substr($shift->jam_mulai, 0, 5) }}–{{ substr($shift->jam_selesai, 0, 5) }})</option>@endforeach</select>@error('shift_id')<p class="mt-1 text-xs text-red-500">{{ $message }}</p>@enderror</div>
                <div><label class="mb-1.5 block text-sm font-semibold text-stone-700">Lokasi Kerja</label><select name="lokasi_kerja_id" required class="w-full rounded-2xl border border-stone-200 bg-white px-4 py-3 text-sm outline-none transition focus:border-amber-500 focus:ring-4 focus:ring-amber-500/15"><option value="">-- Pilih Lokasi --</option>@foreach($locations as $location)<option value="{{ $location->id }}" {{ old('lokasi_kerja_id') == $location->id ? 'selected' : '' }}>{{ $location->nama_lokasi }}</option>@endforeach</select>@error('lokasi_kerja_id')<p class="mt-1 text-xs text-red-500">{{ $message }}</p>@enderror</div>
            </div>
            <div class="flex items-start gap-3 rounded-2xl border border-stone-100 bg-stone-50 px-4 py-3.5"><svg class="mt-0.5 h-5 w-5 flex-shrink-0 text-amber-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="1.9"><path stroke-linecap="round" stroke-linejoin="round" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg><p class="text-xs leading-relaxed text-stone-500">Lokasi pada jadwal menjadi geofence yang digunakan saat karyawan melakukan absen masuk dan pulang.</p></div>
        </div>
        <div class="flex flex-col-reverse gap-3 border-t border-stone-100 px-7 py-5 sm:flex-row sm:justify-end"><a href="{{ route('admin.jadwal.index') }}" class="rounded-2xl border border-stone-200 px-5 py-2.5 text-center text-sm font-semibold text-stone-600 transition hover:bg-stone-50">Batal</a><button type="submit" {{ !$ready ? 'disabled' : '' }} class="rounded-2xl px-6 py-2.5 text-sm font-bold text-white shadow-lg shadow-amber-500/25 transition disabled:cursor-not-allowed disabled:opacity-40" style="background: linear-gradient(135deg, #d97706, #b45309);">Simpan Jadwal</button></div>
    </form>
</div>
@endsection
