@extends("layouts.admin")
@section("title", "Edit Shift Karyawan")
@section("content")
<div class="mx-auto max-w-2xl"><a href="{{ route('admin.jadwal.index') }}" class="mb-4 inline-flex items-center gap-1.5 text-sm font-medium text-stone-500 hover:text-amber-700"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7"/></svg>Kembali ke penempatan shift</a>
<form method="POST" action="{{ route('admin.jadwal.update',$karyawan) }}" class="overflow-hidden rounded-3xl border border-white/70 bg-white/80 shadow-sm">@csrf @method('PUT')
<div class="flex items-center gap-4 border-b border-stone-100 px-7 py-5" style="background:linear-gradient(120deg,#faf5ef,#f5ede3)"><div class="flex h-12 w-12 items-center justify-center rounded-2xl text-sm font-bold text-white" style="background:linear-gradient(135deg,#f59e0b,#d97706)">{{ strtoupper(substr($karyawan->nama_lengkap,0,2)) }}</div><div><h3 class="font-extrabold text-stone-800">{{ $karyawan->nama_lengkap }}</h3><p class="text-xs text-stone-400">{{ $karyawan->jabatan }} · Shift saat ini {{ $karyawan->defaultShift?->nama ?? '-' }}</p></div></div>
<div class="space-y-4 px-7 py-6"><label class="block text-sm font-semibold text-stone-700">Pilih Shift Kerja</label><div class="grid gap-3 sm:grid-cols-2">@foreach($shifts as $shift)<label class="cursor-pointer rounded-2xl border border-stone-200 bg-white p-4 transition has-[:checked]:border-amber-500 has-[:checked]:bg-amber-50 has-[:checked]:ring-4 has-[:checked]:ring-amber-500/10"><input type="radio" name="default_shift_id" value="{{ $shift->id }}" class="sr-only" {{ old('default_shift_id',$karyawan->default_shift_id)==$shift->id?'checked':'' }}><div class="font-bold text-stone-800">Shift {{ $shift->nama }}</div><div class="mt-1 font-mono text-sm text-stone-500">{{ substr($shift->jam_mulai,0,5) }}–{{ substr($shift->jam_selesai,0,5) }}</div><div class="mt-1 text-xs text-stone-400">Toleransi {{ $shift->toleransi_menit }} menit</div></label>@endforeach</div>@error('default_shift_id')<p class="text-xs text-red-500">{{ $message }}</p>@enderror<div class="rounded-2xl border border-amber-100 bg-amber-50/60 p-4 text-xs leading-relaxed text-amber-900">Perubahan diterapkan pada jadwal hari ini dan berikutnya yang belum mempunyai absensi. Histori dan sesi yang sudah berjalan tetap menggunakan shift sebelumnya.</div></div>
<div class="flex justify-end gap-3 border-t border-stone-100 px-7 py-5"><a href="{{ route('admin.jadwal.index') }}" class="rounded-2xl border border-stone-200 px-5 py-2.5 text-sm font-semibold text-stone-600">Batal</a><button class="rounded-2xl px-6 py-2.5 text-sm font-bold text-white" style="background:linear-gradient(135deg,#d97706,#b45309)">Simpan Perubahan Shift</button></div></form></div>
@endsection
