@extends("layouts.admin")
@section("title", "Rincian Payroll")
@section("content")
@php $periodDate = \Carbon\Carbon::create($payroll->periode_tahun, $payroll->periode_bulan, 1); @endphp
<a href="{{ route('admin.payroll.index', ['period' => $periodDate->format('Y-m')]) }}" class="mb-4 inline-flex items-center gap-1.5 text-sm font-medium text-stone-500 transition hover:text-amber-700"><svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7"/></svg>Kembali ke rekap</a>

<div class="mb-5 grid gap-4 lg:grid-cols-3"><div class="rounded-3xl border border-white/70 bg-white/80 p-6 shadow-sm lg:col-span-2"><div class="flex items-center gap-4"><div class="flex h-14 w-14 items-center justify-center rounded-2xl text-base font-bold text-white" style="background:linear-gradient(135deg,#f59e0b,#d97706)">{{ strtoupper(substr($payroll->karyawan->nama_lengkap,0,2)) }}</div><div><h2 class="text-lg font-extrabold text-stone-800">{{ $payroll->karyawan->nama_lengkap }}</h2><p class="text-sm text-stone-500">{{ $payroll->karyawan->jabatan }} · {{ $periodDate->translatedFormat('F Y') }}</p></div></div><div class="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><div class="rounded-2xl bg-stone-50 p-3"><div class="text-lg font-bold">{{ $payroll->total_hadir }}</div><div class="text-[11px] text-stone-400">Sesi selesai</div></div><div class="rounded-2xl bg-stone-50 p-3"><div class="text-lg font-bold">{{ $payroll->total_paid_minutes }}</div><div class="text-[11px] text-stone-400">Menit dibayar</div></div><div class="rounded-2xl bg-stone-50 p-3"><div class="text-lg font-bold">{{ $payroll->total_tidak_lengkap }}</div><div class="text-[11px] text-stone-400">Tidak lengkap</div></div><div class="rounded-2xl bg-amber-50 p-3"><div class="text-lg font-bold text-amber-700">Rp {{ number_format($payroll->total_gaji,0,',','.') }}</div><div class="text-[11px] text-stone-400">Total gaji</div></div></div></div><div class="rounded-3xl bg-stone-800 p-6 text-white"><div class="text-xs font-bold uppercase tracking-wide text-amber-300">Formula Hasil</div><div class="mt-3 rounded-xl bg-white/10 p-3 font-mono text-xs">Total = Σ round(paid_minutes_sesi × {{ number_format($payroll->tarif_per_jam,0,',','.') }} ÷ 60)</div><p class="mt-3 text-xs leading-relaxed text-stone-300">Paid minutes hanya overlap jam hadir dengan jadwal dan dibatasi {{ config('payroll.max_paid_minutes_per_shift') }} menit.</p></div></div>

<div class="overflow-hidden rounded-3xl border border-white/70 bg-white/80 shadow-sm"><div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="border-b border-stone-100 text-left text-[11px] font-bold uppercase tracking-wider text-stone-400"><th class="px-6 py-4">Tanggal/Shift</th><th class="px-6 py-4">Masuk-Pulang</th><th class="px-6 py-4">Durasi Aktual</th><th class="px-6 py-4">Menit Dibayar</th><th class="px-6 py-4">Perhitungan</th><th class="px-6 py-4 text-right">Hasil</th></tr></thead><tbody class="divide-y divide-stone-50">@forelse($sessions as $session)<tr class="hover:bg-amber-50/40"><td class="px-6 py-4"><div class="font-semibold text-stone-700">{{ $session->tanggal->translatedFormat('d M Y') }}</div><div class="text-[11px] text-stone-400">{{ $session->jadwalKerja?->shift?->nama ?? 'Tanpa shift' }}</div></td><td class="px-6 py-4 font-mono text-xs">{{ $session->clock_in_at?->format('H:i') ?? '-' }}–{{ $session->clock_out_at?->format('H:i') ?? '-' }}</td><td class="px-6 py-4">{{ $session->worked_minutes }} menit</td><td class="px-6 py-4"><span class="rounded-full bg-amber-50 px-2.5 py-1 font-mono text-xs font-semibold text-amber-700">{{ $session->paid_minutes }} menit</span></td><td class="px-6 py-4 font-mono text-[11px] text-stone-500">@if($session->status_kehadiran === 'selesai')round({{ $session->paid_minutes }} × {{ number_format($payroll->tarif_per_jam,0,',','.') }} ÷ 60)@elseTidak dihitung: {{ $session->status_kehadiran }}@endif</td><td class="px-6 py-4 text-right font-bold {{ $session->session_salary > 0 ? 'text-amber-700' : 'text-stone-400' }}">Rp {{ number_format($session->session_salary,0,',','.') }}</td></tr>@empty<tr><td colspan="6" class="px-6 py-16 text-center text-sm text-stone-400">Tidak ada sesi absensi pada periode ini.</td></tr>@endforelse</tbody><tfoot><tr class="border-t-2 border-stone-100 bg-stone-50"><td colspan="5" class="px-6 py-4 text-right font-bold text-stone-600">Σ Hasil Per Sesi</td><td class="px-6 py-4 text-right text-base font-extrabold text-amber-700">Rp {{ number_format($sessions->sum('session_salary'),0,',','.') }}</td></tr></tfoot></table></div></div>
@endsection
